### ISSUE TITLE
[FixInsight Warning] ADAPT.Generics.Trees.pas(326): W521 Return value of function 'TADTreeNode<T>.IndexOf' might be undefined

### ISSUE THREAD

**Issue by LK-Daniel** [LaKraven/ADAPT#20]
As the title says, `TADTreeNode<T>.IndexOf` does not return anything yet. It has the TODO item stating

> Need to know the Index of this Node in its Parent's "Children" list.

This is because I've switched from Simon's original approach of referencing implementing Types internally, to referencing public Interface Types internally. I need to associate with each TreeNode its respective Index in its Parent Node's "Child" list.

**Comment by LK-Simon** [comment]
This one is now resolved
