### ISSUE TITLE
Pascal - TADTreeNode<T> needs to define Allocators

### ISSUE THREAD

**Issue by LK-Daniel** [LaKraven/ADAPT#27]
At present, the `TADTreeNode<T>` types don't enable the implementing developer to define what Expander and Compactor "Allocators" to use for the underlying `Children` List (which is an `IADList<T>` type).

To remedy this, we need to provide a similar selection of overloaded constructors such as found in `TADList<T>`, wherein the implementing developer can define their desired Expander and/or Compactor "Allocators".

This is quite important, because different use-cases will necessitate different Allocator behaviours for optimum performance.

**Comment by LK-Simon** [comment]
Don't know what you were on about with "I won't be providing overloaded constructors" because I see no other way of enabling a developer to define the Allocators (Compactor/Expander) to use against a node's Child list.

**Comment by LK-Simon** [comment]
Resolved in 0cb9069
