### ISSUE TITLE
Delphi - FMX - Demo - Precision Threads

### ISSUE THREAD

**Issue by LK-Daniel** [LaKraven/ADAPT#32]
I need to complete the Precision Threads demo for Delphi (FMX)

This demo will enable you to specify some performance-related settings for a Precision Thread, and will graph the actual runtime performance of said Precision Thread on a Form.
In turn, you'll be able to verify that the performance settings you provide are causing the desired behaviour on the Precision Thread.

It's also a good small example of how to define your own Precision Thread types.

**Comment by LK-Simon** [comment]
This demo is largely working, though there is a large memory leak on shutdown which I *think* is being caused by FireMonkey as there are no references to any of the ADAPT library objects in the leak dump.

**Comment by LK-Simon** [comment]
I'm going to create a new (graphically-simpler) Precision Thread Demo, so I'm closing this issue.
